Update dabs

diff --git a/dabs b/dabs
--- a/dabs
+++ b/dabs
@@ -1,10 +1,9 @@
-#!/bin/sh
-
-# Desktop Arch Bootstrapping Script (DABS)
-#
-# Forked from Luke's Auto Rice Bootstrapping Script (LARBS) <larbs.xyz/larbs.sh>
-# by Luke Smith <luke@lukesmith.xyz>
-# License: GNU GPLv3
+#!/bin/bash
+###############################################
+#  DABS - Desktop Arch Bootstrapping Script   #
+#  Based on Luke Smith's LARBS (GNU GPLv3)    #
+#         Customized for ifnot1then0          #
+###############################################
 
 ### OPTIONS AND VARIABLES ###
 
@@ -21,25 +20,23 @@ installpkg() {
 }
 
 error() {
-	# Log to stderr and exit with failure.
 	printf "%s\n" "$1" >&2
 	exit 1
 }
 
 welcomemsg() {
-	whiptail --title "Desktop Arch Bootstrapping Script" \
-		--msgbox "Welcome to DABS installation.\\n\\nThis script will install a fully-featured Arch Linux desktop environment." 10 60
+	whiptail --title "Desktop Arch Bootstrapping Script (DABS)" \
+		--msgbox "Welcome to DABS.\\n\\nThis script will install a fully-featured Arch Linux desktop environment using your personal configuration." 11 65
 
-	whiptail --title "Important Note!" --yes-button "ENTER" \
-		--no-button "EXIT" \
-		--yesno "Ensure this computer has current pacman updates and Arch keyrings.\\n\\nIf not, the installation of some programs might fail." 8 70
+	whiptail --title "Important Note!" --yes-button "Continue" \
+		--no-button "Exit" \
+		--yesno "Ensure this computer has current pacman updates and refreshed Arch keyrings.\\n\\nIf not, the installation of some programs may fail." 9 70
 }
 
 getuserandpass() {
-	# Prompts user for new username and password.
-	name=$(whiptail --inputbox "Enter a username." 10 60 3>&1 1>&2 2>&3 3>&1) || exit 1
+	name=$(whiptail --inputbox "Enter a username (recommended: code)" 10 60 3>&1 1>&2 2>&3 3>&1) || exit 1
 	while ! echo "$name" | grep -q "^[a-z_][a-z0-9_-]*$"; do
-		name=$(whiptail --nocancel --inputbox "Username not valid. Give a username beginning with a letter, with only lowercase letters, - or _." 10 60 3>&1 1>&2 2>&3 3>&1)
+		name=$(whiptail --nocancel --inputbox "Username not valid. Use only lowercase letters, numbers, - or _." 10 60 3>&1 1>&2 2>&3 3>&1)
 	done
 	pass1=$(whiptail --nocancel --passwordbox "Enter a password." 10 60 3>&1 1>&2 2>&3 3>&1)
 	pass2=$(whiptail --nocancel --passwordbox "Retype password." 10 60 3>&1 1>&2 2>&3 3>&1)
@@ -52,22 +49,21 @@ getuserandpass() {
 
 usercheck() {
 	! { id -u "$name" >/dev/null 2>&1; } ||
-		whiptail --title "WARNING" --yes-button "ENTER" \
+		whiptail --title "WARNING" --yes-button "CONTINUE" \
 			--no-button "EXIT" \
-			--yesno "The user \`$name\` already exists. DABS will OVERWRITE any conflicting settings/dotfiles on this account.\\n\\nDABS will NOT overwrite user files, documents, videos, etc., Only click <ENTER> if it's okay to OVERWRITE your current settings.\\n\\nAlso, DABS will change $name's password to the one given." 14 70
+			--yesno "The user \`$name\` already exists. DABS will OVERWRITE conflicting settings/dotfiles.\\n\\nYour personal files will NOT be touched. Continue only if you accept this." 14 70
 }
 
 preinstallmsg() {
-	whiptail --title "Desktop Arch Bootstrapping Script" --yes-button "ENTER" \
-		--no-button "EXIT" \
-		--yesno "The rest of the installation will be automated. It will take some time. Please do not interrupt the installation while in progress.\\n\\n <ENTER> to continue with the installation.\\n\\n <EXIT> to cancel the installation." 13 60 || {
+	whiptail --title "DABS Installation" --yes-button "Continue" \
+		--no-button "Exit" \
+		--yesno "The rest of the installation will now be automated.\\n\\nThis may take a while. Press Continue to begin." 12 60 || {
 		clear
 		exit 1
 	}
 }
 
 adduserandpass() {
-	# Adds user `$name` with password $pass1.
 	whiptail --infobox "Adding user \"$name\"..." 7 50
 	useradd -m -g wheel -s /bin/zsh "$name" >/dev/null 2>&1 ||
 		usermod -a -G wheel "$name" && mkdir -p /home/"$name" && chown "$name":wheel /home/"$name"
@@ -85,9 +81,8 @@ refreshkeys() {
 		pacman --noconfirm -S archlinux-keyring >/dev/null 2>&1
 		;;
 	*)
-		whiptail --infobox "Enabling Arch Repositories for more a more extensive software collection..." 7 40
-		pacman --noconfirm --needed -S \
-			artix-keyring artix-archlinux-support >/dev/null 2>&1
+		whiptail --infobox "Enabling Arch repositories..." 7 40
+		pacman --noconfirm --needed -S artix-keyring artix-archlinux-support >/dev/null 2>&1
 		grep -q "^\[extra\]" /etc/pacman.conf ||
 			echo "[extra]
 Include = /etc/pacman.d/mirrorlist-arch" >>/etc/pacman.conf
@@ -98,8 +93,6 @@ Include = /etc/pacman.d/mirrorlist-arch" >>/etc/pacman.conf
 }
 
 manualinstall() {
-	# Installs $1 manually. Used only for AUR helper here.
-	# Should be run after repodir is created and var is set.
 	pacman -Qq "$1" && return 0
 	whiptail --infobox "Installing \"$1\" manually." 7 50
 	sudo -u "$name" mkdir -p "$repodir/$1"
@@ -110,13 +103,12 @@ manualinstall() {
 			sudo -u "$name" git pull --force origin master
 		}
 	cd "$repodir/$1" || exit 1
-	sudo -u "$name" \
+	sudo -u "$name" -D "$repodir/$1" \
 		makepkg --noconfirm -si >/dev/null 2>&1 || return 1
 }
 
 maininstall() {
-	# Installs all needed programs from main repo.
-	whiptail --title "Desktop Arch Bootstrapping Script" --infobox "Installing \`$1\` ($n of $total). $1 $2" 9 70
+	whiptail --title "DABS Installation" --infobox "Installing \`$1\` ($n of $total). $1 $2" 9 70
 	installpkg "$1"
 }
 
@@ -124,8 +116,8 @@ gitmakeinstall() {
 	progname="${1##*/}"
 	progname="${progname%.git}"
 	dir="$repodir/$progname"
-	whiptail --title "Desktop Arch Bootstrapping Script" \
-		--infobox "Installing \`$progname\` ($n of $total) via \`git\` and \`make\`. $(basename "$1") $2" 8 70
+	whiptail --title "DABS Installation" \
+		--infobox "Installing \`$progname\` ($n of $total) via git + make." 8 70
 	sudo -u "$name" git -C "$repodir" clone --depth 1 --single-branch \
 		--no-tags -q "$1" "$dir" ||
 		{
@@ -139,15 +131,15 @@ gitmakeinstall() {
 }
 
 aurinstall() {
-	whiptail --title "Desktop Arch Bootstrapping Script" \
-		--infobox "Installing \`$1\` ($n of $total) from the AUR. $1 $2" 9 70
+	whiptail --title "DABS Installation" \
+		--infobox "Installing \`$1\` ($n of $total) from the AUR." 9 70
 	echo "$aurinstalled" | grep -q "^$1$" && return 1
 	sudo -u "$name" $aurhelper -S --noconfirm "$1" >/dev/null 2>&1
 }
 
 pipinstall() {
-	whiptail --title "Desktop Arch Bootstrapping Script" \
-		--infobox "Installing the Python package \`$1\` ($n of $total). $1 $2" 9 70
+	whiptail --title "DABS Installation" \
+		--infobox "Installing the Python package \`$1\` ($n of $total)." 9 70
 	[ -x "$(command -v "pip")" ] || installpkg python-pip >/dev/null 2>&1
 	yes | pip install "$1"
 }
@@ -171,8 +163,7 @@ installationloop() {
 }
 
 putgitrepo() {
-	# Downloads a gitrepo $1 and places the files in $2 only overwriting conflicts
-	whiptail --infobox "Downloading and installing config files..." 7 60
+	whiptail --infobox "Downloading and installing your dotfiles..." 7 60
 	[ -z "$3" ] && branch="dot" || branch="$repobranch"
 	dir=$(mktemp -d)
 	[ ! -d "$2" ] && mkdir -p "$2"
@@ -183,176 +174,80 @@ putgitrepo() {
 	sudo -u "$name" cp -rfT "$dir" "$2"
 }
 
-vimplugininstall() {
-	# Installs vim plugins.
-	whiptail --infobox "Installing neovim plugins..." 7 60
-	mkdir -p "/home/$name/.config/nvim/autoload"
-	curl -Ls "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" >  "/home/$name/.config/nvim/autoload/plug.vim"
-	chown -R "$name:wheel" "/home/$name/.config/nvim"
-	sudo -u "$name" nvim -c "PlugInstall|q|q"
-}
-
-makeuserjs(){
-	# Get the Arkenfox user.js and prepare it.
-	arkenfox="$pdir/arkenfox.js"
-	overrides="$pdir/user-overrides.js"
-	userjs="$pdir/user.js"
-	ln -fs "/home/$name/.config/firefox/larbs.js" "$overrides"
-	[ ! -f "$arkenfox" ] && curl -sL "https://raw.githubusercontent.com/arkenfox/user.js/master/user.js" > "$arkenfox"
-	cat "$arkenfox" "$overrides" > "$userjs"
-	chown "$name:wheel" "$arkenfox" "$userjs"
-}
-
-startservices() {
-	systemctl enable sshd.service
-	systemctl enable bluetooth.service
-	systemctl start sshd.service
-	systemctl start bluetooth.service
-}
-
-tidyup() {
-	rm -f /etc/sudoers.d/larbs-temp
-	rm -f /home/$name/install_yay
-}
-
 finalize() {
-	whiptail --title "Desktop Arch Bootstrapping Script" \
-		--msgbox "Complete! Provided there were no hidden errors, the script completed successfully and all the programs and configuration files should be in place.\\n\\nTo run the new graphical environment, log out and log back in as your new user, then run the command \"startx\" to start the graphical environment (it will start automatically in tty1)." 13 80
+	whiptail --title "DABS Complete" \
+		--msgbox "Installation finished successfully.\\n\\nLog out, log back in as your new user, then run:\\n\\n  startx\\n\\n(or it should start automatically on tty1)." 13 70
 }
 
 ### THE ACTUAL SCRIPT ###
 
-### This is how everything happens in an intuitive format and order.
-
-# Check if user is root on Arch distro. Install whiptail.
 pacman --noconfirm --needed -Sy libnewt ||
-	error "Are you sure you're running this as the root user, are on an Arch-based distribution and have an internet connection?"
+	error "Are you sure you're running this as root on an Arch-based system with internet?"
 
-# Welcome user and pick dotfiles.
 welcomemsg || error "User exited."
-
-# Get and verify username and password.
 getuserandpass || error "User exited."
-
-# Give warning if user already exists.
 usercheck || error "User exited."
-
-# Last chance for user to back out before install.
 preinstallmsg || error "User exited."
 
-### The rest of the script requires no user input.
-
-# Refresh Arch keyrings.
 refreshkeys ||
-	error "Error automatically refreshing Arch keyring. Consider doing so manually."
+	error "Error refreshing Arch keyring. Try doing it manually."
 
 for x in curl ca-certificates base-devel git ntp zsh dash; do
-	whiptail --title "Desktop Arch Bootstrapping Script" \
-		--infobox "Installing \`$x\` which is required to install and configure other programs." 8 70
+	whiptail --title "DABS Installation" \
+		--infobox "Installing \`$x\` (required)..." 8 70
 	installpkg "$x"
 done
 
-whiptail --title "Desktop Arch Bootstrapping Script" \
-	--infobox "Synchronizing system time to ensure successful and secure installation of software..." 8 70
+whiptail --title "DABS Installation" \
+	--infobox "Synchronizing system time..." 8 70
 ntpd -q -g >/dev/null 2>&1
 
 adduserandpass || error "Error adding username and/or password."
 
-[ -f /etc/sudoers.pacnew ] && cp /etc/sudoers.pacnew /etc/sudoers # Just in case
+[ -f /etc/sudoers.pacnew ] && cp /etc/sudoers.pacnew /etc/sudoers
 
-# Allow user to run sudo without password. Since AUR programs must be installed
-# in a fakeroot environment, this is required for all builds with AUR.
 trap 'rm -f /etc/sudoers.d/larbs-temp' HUP INT QUIT TERM PWR EXIT
 echo "%wheel ALL=(ALL) NOPASSWD: ALL
 Defaults:%wheel,root runcwd=*" >/etc/sudoers.d/larbs-temp
 
-# Make pacman colorful, concurrent downloads and Pacman eye-candy.
 grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
 sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf
-
-# Use all cores for compilation.
 sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf
 
 manualinstall $aurhelper || error "Failed to install AUR helper."
 
-# Make sure .*-git AUR packages get updated automatically.
 $aurhelper -Y --save --devel
 
-# The command that does all the installing. Reads the progs.csv file and
-# installs each needed program the way required. Be sure to run this only after
-# the user has been created and has priviledges to run sudo without a password
-# and all build dependencies are installed.
 installationloop
 
-# Install the dotfiles in the user's home directory, but remove .git dir and
-# other unnecessary files.
 putgitrepo "$dotfilesrepo" "/home/$name" "$repobranch"
 rm -rf "/home/$name/.git/"
 
-# Install vim plugins if not alread present.
-[ ! -f "/home/$name/.config/nvim/autoload/plug.vim" ] && vimplugininstall
-
-# Most important command! Get rid of the beep!
 rmmod pcspkr
 echo "blacklist pcspkr" >/etc/modprobe.d/nobeep.conf
 
-# Make zsh the default shell for the user.
 chsh -s /bin/zsh "$name" >/dev/null 2>&1
 sudo -u "$name" mkdir -p "/home/$name/.cache/zsh/"
 sudo -u "$name" mkdir -p "/home/$name/.config/abook/"
 sudo -u "$name" mkdir -p "/home/$name/.config/mpd/playlists/"
 
-# Make dash the default #!/bin/sh symlink.
 ln -sfT /bin/dash /bin/sh >/dev/null 2>&1
-
-# dbus UUID must be generated for Artix runit.
 dbus-uuidgen >/var/lib/dbus/machine-id
 
-# Use system notifications for Brave on Artix
-# Only do it when systemd is not present
-[ "$(readlink -f /sbin/init)" != "/usr/lib/systemd/systemd" ] && echo "export \$(dbus-launch)" >/etc/profile.d/dbus.sh
-
-# Enable tap to click
 [ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
         Identifier "libinput touchpad catchall"
         MatchIsTouchpad "on"
         MatchDevicePath "/dev/input/event*"
         Driver "libinput"
-	# Enable left mouse button by tapping
 	Option "Tapping" "on"
 EndSection' >/etc/X11/xorg.conf.d/40-libinput.conf
 
-# All this below to get Librewolf installed with add-ons and non-bad settings.
-
-whiptail --infobox "Setting browser privacy settings and add-ons..." 7 60
-
-browserdir="/home/$name/.librewolf"
-profilesini="$browserdir/profiles.ini"
-
-# Start librewolf headless so it generates a profile. Then get that profile in a variable.
-sudo -u "$name" librewolf --headless >/dev/null 2>&1 &
-sleep 1
-profile="$(sed -n "/Default=.*.default-default/ s/.*=//p" "$profilesini")"
-pdir="$browserdir/$profile"
-
-[ -d "$pdir" ] && makeuserjs
-
-# Kill the now unnecessary librewolf instance.
-pkill -u "$name" librewolf
-
-# Allow wheel users to sudo with password and allow several system commands
-# (like `shutdown` to run without password).
-echo "%wheel ALL=(ALL:ALL) ALL" >/etc/sudoers.d/00-larbs-wheel-can-sudo
-echo "%wheel ALL=(ALL:ALL) NOPASSWD: /usr/bin/light,/usr/bin/shutdown,/usr/bin/reboot,/usr/bin/systemctl suspend,/usr/bin/wifi-menu,/usr/bin/mount,/usr/bin/umount,/usr/bin/pacman -Syu,/usr/bin/pacman -Syyu,/usr/bin/pacman -Syyu --noconfirm,/usr/bin/loadkeys,/usr/bin/pacman -Syyuw --noconfirm,/usr/bin/pacman -S -y --config /etc/pacman.conf --,/usr/bin/pacman -S -y -u --config /etc/pacman.conf --" >/etc/sudoers.d/01-larbs-cmds-without-password
-echo "Defaults editor=/usr/bin/nvim" >/etc/sudoers.d/02-larbs-visudo-editor
+echo "%wheel ALL=(ALL:ALL) ALL" >/etc/sudoers.d/00-dabs-wheel-can-sudo
+echo "%wheel ALL=(ALL:ALL) NOPASSWD: /usr/bin/light,/usr/bin/shutdown,/usr/bin/reboot,/usr/bin/systemctl suspend,/usr/bin/wifi-menu,/usr/bin/mount,/usr/bin/umount,/usr/bin/pacman -Syu,/usr/bin/pacman -Syyu,/usr/bin/pacman -Syyu --noconfirm,/usr/bin/loadkeys,/usr/bin/pacman -Syyuw --noconfirm,/usr/bin/pacman -S -y --config /etc/pacman.conf --,/usr/bin/pacman -S -y -u --config /etc/pacman.conf --" >/etc/sudoers.d/01-dabs-cmds-without-password
+echo "Defaults editor=/usr/bin/nvim" >/etc/sudoers.d/02-dabs-visudo-editor
 mkdir -p /etc/sysctl.d
 echo "kernel.dmesg_restrict = 0" > /etc/sysctl.d/dmesg.conf
 
-# Enable and start up systemd services
-startservices
+rm -f /etc/sudoers.d/larbs-temp
 
-# Clean up and start services
-tidyup
-
-# Last message! Install complete!
 finalize
